move version out of makefile

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -699,20 +699,63 @@ fi
 posix_make && Q_ASSIGN="=" || Q_ASSIGN="?="
 
 # detect source directories
+start_check "sources"
+HAS_RHASH=no
+HAS_LIBRHASH=no
+HAS_BINDINGS=no
+RHASH_VERSION=
+BINDINGS_VERSION=
 RHASH_SRC=
 LIBRHASH_SRC=
+BINDINGS_SRC=
+SRC_FOUND=no
+test -f Makefile || die "Makefile not found"
 if test -f rhash_main.c; then
-  RHASH_SRC=.
-  test -d librhash && LIBRHASH_SRC=librhash
+  HAS_RHASH=yes
+  SRC_FOUND=RHash
+  if test -d librhash; then
+    HAS_LIBRHASH=yes
+    LIBRHASH_SRC=librhash/
+  fi
+  if test -f bindings/version.properties; then
+    HAS_BINDINGS=yes
+    BINDINGS_SRC=bindings/
+  fi
 elif test -f rhash.c; then
-  LIBRHASH_SRC=.
-else
-  die "sources not found"
+  HAS_LIBRHASH=yes
+  SRC_FOUND=LibRHash
+elif test -f version.properties; then
+  HAS_BINDINGS=yes
+  SRC_FOUND="RHash bindings"
+fi
+echo "RHASH_SRC=$RHASH_SRC, LIBRHASH_SRC=$LIBRHASH_SRC, BINDINGS_SRC=$BINDINGS_SRC" >> "$TMPLOG"
+
+# check version
+good_version() { echo "$1" | grep -q '^[1-9]\.[1-9][0-9]*\.[1-9]' ; }
+if test "$HAS_RHASH" = "yes"; then
+  test -f "${RHASH_SRC}version.h" || die "${RHASH_SRC}version.h not found"
+  RHASH_VERSION=$(cut -d'"' -f2 "${RHASH_SRC}version.h")
+  echo "RHASH_VERSION=$RHASH_VERSION" >> "$TMPLOG"
+  good_version "$RHASH_VERSION" || die "wrong version: $RHASH_VERSION"
+fi
+if test "$HAS_BINDINGS" = "yes"; then
+  BINDINGS_VERSION=$(cut -d = -f 2 "${BINDINGS_SRC}version.properties")
+  echo "BINDINGS_VERSION=$BINDINGS_VERSION" >> "$TMPLOG"
+  good_version "$BINDINGS_VERSION" || die "wrong bindings version: $BINDINGS_VERSION"
+  test -z "$RHASH_VERSION" && RHASH_VERSION="$BINDINGS_VERSION"
+fi
+test -n "$RHASH_VERSION" && SRC_FOUND="$SRC_FOUND $RHASH_VERSION"
+finish_check "$SRC_FOUND"
+test "$SRC_FOUND" = "no" && die "sources not found"
+
+if test "$HAS_BINDINGS" = "yes" && test "$BINDINGS_VERSION" != "$RHASH_VERSION"; then
+  echo "Updating ${BINDINGS_SRC}version.properties"
+  echo "version=$RHASH_VERSION" > ${BINDINGS_SRC}version.properties
 fi
 
-if test -n "$RHASH_SRC"; then
-  echo "Writing "$(echo $RHASH_SRC/config.mak | sed -e 's/\.\///')
-  cat > $RHASH_SRC/config.mak << EOF
+if test "$HAS_RHASH" = "yes"; then
+  echo "Writing ${RHASH_SRC}config.mak"
+  cat > ${RHASH_SRC}config.mak << EOF
 # -------- Generated by configure -----------
 
 DESTDIR $Q_ASSIGN
@@ -728,6 +771,7 @@ INSTALL = $CMD_INSTALL
 LIBRHASH_STATIC = librhash/$LIBRHASH_STATIC
 LIBRHASH_SHARED = librhash/$LIBRHASH_SHARED
 BUILD_TYPE      = $RHASH_BUILD_TYPE
+VERSION         = $RHASH_VERSION
 EXEC_EXT        = $EXEC_EXT
 RHASH_STATIC    = $RHASH_STATIC\$(EXEC_EXT)
 RHASH_SHARED    = $RHASH_SHARED\$(EXEC_EXT)
@@ -748,9 +792,9 @@ EOF
 fi
 
 
-if test -n "$LIBRHASH_SRC"; then
-  echo "Writing "$(echo $LIBRHASH_SRC/config.mak | sed -e 's/\.\///')
-  cat > $LIBRHASH_SRC/config.mak << EOF
+if test "$HAS_LIBRHASH" = "yes"; then
+  echo "Writing ${LIBRHASH_SRC}config.mak"
+  cat > ${LIBRHASH_SRC}config.mak << EOF
 # -------- Generated by configure -----------
 
 DESTDIR $Q_ASSIGN
